/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation("software.momento.java:sdk:1.4.0")
    implementation("com.amazonaws:dynamodb-lock-client:1.2.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.0")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.0")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.0")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("commons-logging:commons-logging:1.2")
    implementation("software.amazon.awssdk:aws-core:2.20.8")
    implementation("software.amazon.awssdk:dynamodb:2.20.8")
    implementation("software.amazon.awssdk:sdk-core:2.20.8")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.3")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.3")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.named("analyzeTestClassesDependencies").configure {
    enabled = false
}
