/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.amazonaws.services.dynamodbv2;

import com.amazonaws.services.dynamodbv2.model.LockCurrentlyUnavailableException;
import com.amazonaws.services.dynamodbv2.model.LockNotGrantedException;
import com.amazonaws.services.dynamodbv2.util.LockClientUtils;
import momento.lock.client.LockItemUtils;
import momento.lock.client.LockStorage;
import momento.lock.client.MomentoDynamoDBLockClientOptions;
import momento.lock.client.MomentoLockClient;
import momento.lock.client.MomentoLockClientHeartbeatHandler;
import momento.lock.client.MomentoLockItem;
import momento.lock.client.NoopDynamoDbClient;
import momento.lock.client.model.MomentoClientException;
import momento.sdk.CacheClient;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import software.amazon.awssdk.core.exception.SdkClientException;

import java.io.Closeable;
import java.io.IOException;
import java.time.Duration;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import java.util.stream.Stream;

public class MomentoDynamoDBLockClient extends AmazonDynamoDBLockClient implements Closeable  {
    private static final Log logger = LogFactory.getLog(MomentoDynamoDBLockClient.class);

    private final String lockCacheName;
    private final CacheClient cacheClient;
    private static final long DEFAULT_BUFFER_MS = 1000;
    private static final int TTL_GRACE_MILLIS = 200;

    private final long leaseDurationMillis;
    private final long heartbeatPeriodInMilliseconds;
    private final String owner;
    private final ConcurrentHashMap<String, Thread> sessionMonitors;
    private final LockStorage lockStorage;
    private final Function<String, ThreadFactory> namedThreadCreator;

    private ScheduledExecutorService heartbeatExecutor;
    private MomentoLockClientHeartbeatHandler heartbeatHandler;


    private final MomentoLockClient momentoLockClient;
    private final Boolean holdLockOnServiceUnavailable;

    private final ScheduledExecutorService executorService;

    public MomentoDynamoDBLockClient(final MomentoDynamoDBLockClientOptions lockClientOptions) {
        super(AmazonDynamoDBLockClientOptions.builder(new NoopDynamoDbClient(), lockClientOptions.getCacheName()).build());
        Objects.requireNonNull(lockClientOptions.getTableName(), "Table name cannot be null");
        Objects.requireNonNull(lockClientOptions.getCacheName(), "Table name cannot be null");
        Objects.requireNonNull(lockClientOptions.getOwnerName(), "Owner name cannot be null");
        Objects.requireNonNull(lockClientOptions.getTimeUnit(), "Time unit cannot be null");
        Objects.requireNonNull(lockClientOptions.getPartitionKeyName(), "Partition Key Name cannot be null");
        Objects.requireNonNull(lockClientOptions.getSortKeyName(), "Sort Key Name cannot be null (use Optional.absent())");
        Objects.requireNonNull(lockClientOptions.getNamedThreadCreator(), "Named thread creator cannot be null");

        this.lockCacheName = lockClientOptions.getCacheName();

        this.sessionMonitors = new ConcurrentHashMap<>();
        this.owner = lockClientOptions.getOwnerName();
        this.leaseDurationMillis = lockClientOptions.getTimeUnit().toMillis(lockClientOptions.getLeaseDuration());

        this.heartbeatPeriodInMilliseconds = lockClientOptions.getTimeUnit().toMillis(lockClientOptions.getHeartbeatPeriod());
        this.namedThreadCreator = lockClientOptions.getNamedThreadCreator();
        this.holdLockOnServiceUnavailable = lockClientOptions.getHoldLockOnServiceUnavailable();
        this.cacheClient = CacheClient.create(lockClientOptions.getCredentialProvider(),
                lockClientOptions.getConfiguration(), Duration.ofMillis(this.leaseDurationMillis));

        this.momentoLockClient = new MomentoLockClient(cacheClient, lockCacheName);
        this.lockStorage = new LockStorage();


        this.heartbeatHandler = new MomentoLockClientHeartbeatHandler(this.lockStorage,
                this.cacheClient, this.lockCacheName, Duration.ofMillis(leaseDurationMillis),
                holdLockOnServiceUnavailable);

        if (lockClientOptions.getCreateHeartbeatBackgroundThread()) {
            if (this.leaseDurationMillis < 2 * this.heartbeatPeriodInMilliseconds) {
                throw new IllegalArgumentException("Heartbeat period must be no more than half the length of the Lease Duration, "
                        + "or locks might expire due to the heartbeat thread taking too long to update them (recommendation is to make it much greater, for example "
                        + "4+ times greater)");
            }

            this.heartbeatExecutor = new ScheduledThreadPoolExecutor(1);
            heartbeatExecutor.scheduleAtFixedRate(this.heartbeatHandler,
                    0, heartbeatPeriodInMilliseconds, TimeUnit.MILLISECONDS);

        }
        this.executorService = new ScheduledThreadPoolExecutor(10);

    }

    public Stream<LockItem> getAllLocksFromDynamoDB(final boolean deleteOnRelease) {
        throw new UnsupportedOperationException("This operation is not available on" +
                " Momento DynamoDB lock client");
    }

    public Stream<LockItem> getLocksByPartitionKey(String key, final boolean deleteOnRelease) {
        throw new UnsupportedOperationException("This operation is not available on" +
                " Momento DynamoDB lock client");
    }

    public void createLockCache(final String cacheName) {
        try {
            momentoLockClient.createLockCache(cacheName);
        } catch (MomentoClientException e) {
            throw SdkClientException.create(e.getMessage(), e.getCause());
        }
    }

    public LockItem acquireLock(final AcquireLockOptions options) throws LockNotGrantedException, InterruptedException {
        try {
            final String partitionKey = options.getPartitionKey();
            final Optional<String> sortKey = options.getSortKey();

            String cacheKey = generateCacheKey(partitionKey, sortKey);

            if (options.getReentrant()) {
                Optional<LockItem> localLock = lockStorage.getLock(cacheKey);
                if (localLock.isPresent()) {
                    Optional<MomentoLockItem> lockFromMomento = momentoLockClient.getLockFromMomento(cacheKey);
                    if (lockFromMomento.isPresent() && lockFromMomento.get().getOwner().equals(this.owner)) {
                        return localLock.get();
                    }
                }
            }

            validateAttributes(options, partitionKey, sortKey);

            long millisecondsToWait = DEFAULT_BUFFER_MS;
            if (options.getAdditionalTimeToWaitForLock() != null) {
                Objects.requireNonNull(options.getTimeUnit(), "timeUnit must not be null if additionalTimeToWaitForLock is non-null");
                millisecondsToWait = options.getTimeUnit().toMillis(options.getAdditionalTimeToWaitForLock());
            }

            // ddb lock client does this too for default case
            millisecondsToWait += this.leaseDurationMillis;

            long refreshPeriodInMilliseconds = DEFAULT_BUFFER_MS;
            if (options.getRefreshPeriod() != null) {
                Objects.requireNonNull(options.getTimeUnit(), "timeUnit must not be null if refreshPeriod is non-null");
                refreshPeriodInMilliseconds = options.getTimeUnit().toMillis(options.getRefreshPeriod());
            }

            final Optional<SessionMonitor> sessionMonitor = options.getSessionMonitor();
            if (sessionMonitor.isPresent()) {
                sessionMonitorArgsValidate(sessionMonitor.get().getSafeTimeMillis(), this.heartbeatPeriodInMilliseconds,
                        this.leaseDurationMillis);
            }


            return acquireLockWithRetries(options, cacheKey, millisecondsToWait, refreshPeriodInMilliseconds);
        } catch (ExecutionException e) {
            Throwable t = e.getCause();
            if (t instanceof LockCurrentlyUnavailableException) {
                throw new LockCurrentlyUnavailableException(e.getMessage());
            }
            if (t instanceof LockNotGrantedException) {
                throw new LockNotGrantedException(e.getMessage());
            }
            throw SdkClientException.create(t.getMessage(), t.getCause());
        } catch (InterruptedException e) {
            throw SdkClientException.create(e.getMessage(), e.getCause());
        }
    }

    private static String generateCacheKey(String partitionKey, Optional<String> sortKey) {
        String cacheKey = partitionKey;
        if (sortKey.isPresent()) {
            cacheKey = cacheKey + "_" + sortKey.get();
        }
        return cacheKey;
    }

    private LockItem acquireLockWithRetries(final AcquireLockOptions options, final String cacheKey,
                                            final long totalWaitTime, final long waitTimeIfLockAcquired) throws InterruptedException, ExecutionException {
        final long startTimeMillis = LockClientUtils.INSTANCE.millisecondTime();

        // supported rvn is constant cacheKey for now
        final LockItem lockItem = new LockItem(this, options.getPartitionKey(), options.getSortKey(), options.getData(), options.getDeleteLockOnRelease(),
                owner, leaseDurationMillis, startTimeMillis, cacheKey /* rvn */, false /* isReleased */,
                options.getSessionMonitor(), options.getAdditionalAttributes());

        long delay = 0;

        while (true) {

            final ScheduledFuture<LockItem> future = executorService.schedule(() -> {
                logger.trace("Call Momento Get to see if the lock for key = " + cacheKey + "exists in the cache");

                final Optional<MomentoLockItem> lockFromMomento = momentoLockClient.getLockFromMomento(cacheKey);

                        if (!lockFromMomento.isPresent() && options.getAcquireOnlyIfLockAlreadyExists()) {
                            throw new LockNotGrantedException("Lock does not exist.");
                        }

                        if (lockFromMomento.isPresent()) {

                            if (options.shouldSkipBlockingWait()) {
                                /*
                                 * The lock is being held by someone else, and the caller explicitly said not to perform a blocking wait;
                                 * We will throw back a lock not grant exception, so that the caller can retry if needed.
                                 */
                                throw new LockCurrentlyUnavailableException("The lock being requested is being held by another client.");
                            }
                        }

                        boolean acquired = momentoLockClient.acquireLockInMomento(LockItemUtils.toMomentoLockItem(lockItem));

                        if (acquired) return lockItem;
                        else {
                            if (LockClientUtils.INSTANCE.millisecondTime() - startTimeMillis > totalWaitTime) {
                                throw new LockNotGrantedException("Didn't acquire lock after sleeping for " + (LockClientUtils.INSTANCE.millisecondTime() - startTimeMillis) + " milliseconds");
                            }
                            logger.debug("Someone else has the lock for key " + cacheKey + " .I will block until the " +
                                    " lease duration plus the configured timeout through additionalTimeToWaitForLock" );
                            return null;
                        }

                    }, delay, TimeUnit.MILLISECONDS);

            final LockItem item = future.get();

            if (item == null) {
                // this will enter only once if the first attempt to acquire the lock failed.
                if (delay == 0) {
                    delay = waitTimeIfLockAcquired;
                }
            } else {
                lockStorage.addLock(cacheKey, item);
                this.tryAddSessionMonitor(cacheKey, item);
                return item;
            }
        }
    }


    private static void validateAttributes(AcquireLockOptions options, String partitionKey, Optional<String> sortKey) {
        if (options.getAdditionalAttributes().containsKey(partitionKey) || options.getAdditionalAttributes().containsKey(OWNER_NAME) || options
                .getAdditionalAttributes().containsKey(LEASE_DURATION) || options.getAdditionalAttributes().containsKey(RECORD_VERSION_NUMBER) || options
                .getAdditionalAttributes().containsKey(DATA) || sortKey.isPresent() && options.getAdditionalAttributes().containsKey(sortKey.get())) {
            throw new IllegalArgumentException(String
                    .format("Additional attribute cannot be one of the following types: " + "%s, %s, %s, %s, %s", partitionKey, OWNER_NAME, LEASE_DURATION,
                            RECORD_VERSION_NUMBER, DATA));
        }
    }

    public boolean hasLock(final String key, final Optional<String> sortKey) {
        String cacheKey = generateCacheKey(key, sortKey);
        return lockStorage.hasLock(cacheKey);
    }

    public boolean lockTableExists() {
        try {
            return momentoLockClient.lockCacheExists(this.tableName);
        } catch (MomentoClientException e) {
            throw SdkClientException.create(e.getMessage(), e.getCause());
        }
    }

    public Optional<LockItem> tryAcquireLock(final AcquireLockOptions options) throws InterruptedException {
        try {
            return Optional.of(this.acquireLock(options));
        } catch (final LockNotGrantedException x) {
            return Optional.empty();
        }
    }

    private void tryAddSessionMonitor(final String lockName, final LockItem lock) {
        if (lock.hasSessionMonitor() && lock.hasCallback()) {
            final Thread monitorThread = lockSessionMonitorChecker(lockName, lock);
            monitorThread.setDaemon(true);
            monitorThread.start();
            this.sessionMonitors.put(lockName, monitorThread);
        }
    }

    private Thread lockSessionMonitorChecker(final String monitorName, final LockItem lock) {
        return namedThreadCreator.apply(monitorName + "-sessionMonitor").newThread(() -> {
            while (true) {
                try {
                    final long millisUntilDangerZone = lock.millisecondsUntilDangerZoneEntered();
                    if (millisUntilDangerZone > 0) {
                        Thread.sleep(millisUntilDangerZone);
                    } else {
                        lock.runSessionMonitor();
                        sessionMonitors.remove(monitorName);
                        return;
                    }
                } catch (final InterruptedException e) {
                    return;
                }
            }
        });
    }

    public Optional<LockItem> getLock(final String key, final Optional<String> sortKey) {
        String cacheKey = generateCacheKey(key, sortKey);
        Optional<MomentoLockItem> momentoLockItem = momentoLockClient.getLockFromMomento(cacheKey);
        if (momentoLockItem.isPresent()) {
            MomentoLockItem item = momentoLockItem.get();
            return Optional.of(new LockItem(this,
                    item.getPartitionKey(),
                    Optional.ofNullable(item.getSortKey()), Optional.ofNullable(item.getData()),
                    item.getDeleteLockOnRelease(),
                    item.getOwner(),
                    item.getLeaseDuration(), LockClientUtils.INSTANCE.millisecondTime(),
                    item.getPartitionKey(), item.isReleased(), Optional.empty(), item.getAdditionalData()));

        }
        return Optional.empty();
    }

    public boolean releaseLock(final LockItem item) {
        Objects.requireNonNull(item, "LockItem cannot be null");

        return releaseLock(ReleaseLockOptions.builder(item).
                withDeleteLock(item.getDeleteLockItemOnClose()).build());
    }

    public boolean releaseLock(final ReleaseLockOptions options) {
        Objects.requireNonNull(options, "ReleaseLockOptions cannot be null");

        final LockItem lockItem = options.getLockItem();
        final String partitionKey = lockItem.getPartitionKey();
        final Optional<String> sortKey = lockItem.getSortKey();

        String cacheKey = generateCacheKey(partitionKey, sortKey);

        /**
         * When releasing a lock, we aren't explicitly calling delete on momento unless client requested it (default is true).
         * We simply remove the lock from being a heartbeating candidate. This essentially means that the lock
         * will be unavailable until it expires. Other threads who want to acquire the lock will block
         * on it until the lease duration expires unless they have been explicitly asked not to. This
         * is better than accidentally calling delete on a lock owned by this client that's already expired
         * but has been acquired by someone else.
         *
         * TODO: call delete on Momento when we can conditionally update/delete an item.
         */

        boolean deleted = lockStorage.removeLock(cacheKey);

        if (deleted && lockItem.getDeleteLockItemOnClose()) {
            final MomentoLockItem momentoLockItem =
                    LockItemUtils.toMomentoLockItem(lockItem);
            try {
                long remainingTtl = momentoLockClient.getLockRemainingTtl(momentoLockItem);
                // only delete if owner is same and remaining ttl is greater than a window
                // to reduce the probability of a race resulting in us deleting someone else's
                // lock
                if (remainingTtl > TTL_GRACE_MILLIS) {
                    final Optional<MomentoLockItem> item = momentoLockClient.getLockFromMomento(momentoLockItem.getCacheKey());
                    if (item.isPresent() && item.get().getOwner().equals(this.owner)) {
                        momentoLockClient.deleteLockFromMomento(LockItemUtils.toMomentoLockItem(lockItem));
                    }
                }
            } catch (MomentoClientException e) {
                // if not best effort just skip releasing for expiration
                if (!options.isBestEffort()) {
                    throw SdkClientException.create(e.getMessage(), e.getCause());
                }
            }
        }
        return deleted;
    }

    private void releaseAllLocks() {
        this.lockStorage.getAllLocks().forEach(l -> releaseLock(
                ReleaseLockOptions.builder(l).withBestEffort(true).build()
        ));
        this.heartbeatExecutor.shutdown();
        this.executorService.shutdown();
    }

    public void sendHeartbeat(final LockItem lockItem) {
        this.heartbeatHandler.heartBeat(lockItem, LockItemUtils.toMomentoLockItem(lockItem));
    }

    public void sendHeartbeat(final SendHeartbeatOptions options) {
        Objects.requireNonNull(options, "options is required");
        Objects.requireNonNull(options.getLockItem(), "Cannot send heartbeat for null lock");
        this.sendHeartbeat(options.getLockItem());
    }

    @Override
    public void close() throws IOException {
        this.releaseAllLocks();
        this.cacheClient.close();
    }

    private static void sessionMonitorArgsValidate(final long safeTimeWithoutHeartbeatMillis, final long heartbeatPeriodMillis, final long leaseDurationMillis)
            throws IllegalArgumentException {
        if (safeTimeWithoutHeartbeatMillis <= heartbeatPeriodMillis) {
            throw new IllegalArgumentException("safeTimeWithoutHeartbeat must be greater than heartbeat frequency");
        } else if (safeTimeWithoutHeartbeatMillis >= leaseDurationMillis) {
            throw new IllegalArgumentException("safeTimeWithoutHeartbeat must be less than the lock's lease duration");
        }
    }
}
